### ISSUE TITLE
Combining data CSVs

### ISSUE THREAD

**Issue by eboylestanley** [UBC-MDS/525-Group19#4]
1. Use one of the following options to combine data CSVs into a single CSV.
Pandas
DASK
2. When combining the csv files make sure to add extra column called "model" that identifies the model (tip : you can get this column populated from the file name eg: for file name "SAM0-UNICON_daily_rainfall_NSW.csv", the model name is SAM0-UNICON)
3. Compare run times and memory usages of these options on different machines within your team, and summarize your observations in your milestone notebook.

**Comment by eboylestanley** [comment]
Completed 1 & 2 with #7.   Chose to use Pandas to combine files. 

Regarding point 3, run time and memory usage on my Windows machine:
![image](https://user-images.githubusercontent.com/63200505/113176411-71253180-921a-11eb-8dd1-5393d21e6d69.png)

Note that under Win32, system time is always reported as 0, since it can not be measured. - per https://ipython.readthedocs.io/en/stable/interactive/magics.html

**Comment by chiragrank** [comment]
Run time and Memory usage on Ubuntu 20.04.1 LTS
![image](https://user-images.githubusercontent.com/25333663/113439247-31944c00-93b8-11eb-9f4d-4a767ba1bd04.png)

**Comment by roycezhou** [comment]
<img width="295" alt="Screenshot 2021-04-02 at 10 38 33" src="https://user-images.githubusercontent.com/34122673/113439629-ca6a9d80-939f-11eb-9919-1adb9ad127c1.png">

**Comment by HazelJJJ** [comment]
Run time and Memory usage on Windows
![29161ed9ad26b9a9a25a0994846545b](https://user-images.githubusercontent.com/65373316/113440860-11f22900-93a2-11eb-9d66-c066d031bea9.png)
